/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DesktopFrame.java
 *
 * Created on 16/07/2010, 23:31:51
 */

package shapefile;

import java.awt.BorderLayout;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/**
 *
 * @author Carlos
 */
public class DesktopFrame extends javax.swing.JFrame {

    DisplayShapefile shapeView;
    /** Creates new form DesktopFrame */
    public DesktopFrame() {
        super("Visualizador de Dados Geoespaciais");
        initComponents();
        Arquivo.setMnemonic('A');
        Abrir.setMnemonic('b');
        Sair.setMnemonic('S');
        scale.setText("");
        scale.setEditable(false);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ToolBar = new javax.swing.JToolBar();
        increaseZoom = new javax.swing.JButton();
        decreaseZoom = new javax.swing.JButton();
        desktopPane = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        scale = new javax.swing.JTextArea();
        MenuBar = new javax.swing.JMenuBar();
        Arquivo = new javax.swing.JMenu();
        Abrir = new javax.swing.JMenuItem();
        Sair = new javax.swing.JMenuItem();
        Editar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ToolBar.setRollover(true);

        increaseZoom.setText("Zoom +");
        increaseZoom.setFocusable(false);
        increaseZoom.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        increaseZoom.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        increaseZoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                increaseZoomActionPerformed(evt);
            }
        });
        ToolBar.add(increaseZoom);

        decreaseZoom.setText("Zoom -");
        decreaseZoom.setFocusable(false);
        decreaseZoom.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        decreaseZoom.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        decreaseZoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decreaseZoomActionPerformed(evt);
            }
        });
        ToolBar.add(decreaseZoom);

        scale.setColumns(20);
        scale.setRows(5);
        jScrollPane1.setViewportView(scale);

        Arquivo.setText("Arquivo");

        Abrir.setText("Abrir");
        Abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirActionPerformed(evt);
            }
        });
        Arquivo.add(Abrir);

        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        Arquivo.add(Sair);

        MenuBar.add(Arquivo);

        Editar.setText("Editar");
        MenuBar.add(Editar);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(desktopPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void decreaseZoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decreaseZoomActionPerformed
        if (shapeView != null){
            shapeView.decreaseZoom();
        }
        double escala = 1/shapeView.getShapeScale();
        scale.setText("1/" + Double.toString(escala) );
        //scale.setText(Double.toString(shapeView.getShapeScale()));
    }//GEN-LAST:event_decreaseZoomActionPerformed

    private void increaseZoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_increaseZoomActionPerformed
        if (shapeView != null) {
            shapeView.increaseZoom();
        }
        double escala = 1/shapeView.getShapeScale();
        scale.setText("1/" + Double.toString(escala) );
        //scale.setText(Double.toString(shapeView.getShapeScale()));
    }//GEN-LAST:event_increaseZoomActionPerformed

    private void AbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirActionPerformed
        File shapeFile = getFile();
        URL s;
        try {
            s = shapeFile.toURL();
            shapeView = new DisplayShapefile(s);
            shapeView.setSize(640, 640);
            desktopPane.add(shapeView);
            shapeView.setVisible(true);
        } catch (IOException ex) {
            //Logger.getLogger(Desktop.class.getName()).log(Level.SEVERE, null, ex);
        }
        double escala = 1/shapeView.getShapeScale();
        scale.setText("1/" + Double.toString(escala) );
}//GEN-LAST:event_AbrirActionPerformed

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        Object[] options = {"Sim", "Nao"};
        int n = JOptionPane.showOptionDialog(desktopPane,
                "Deseja realmente sair?",
                "Sair",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                options,
                options[0]);
        if (n == 0)
            System.exit(0);
}//GEN-LAST:event_SairActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Abrir;
    private javax.swing.JMenu Arquivo;
    private javax.swing.JMenu Editar;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenuItem Sair;
    private javax.swing.JToolBar ToolBar;
    private javax.swing.JButton decreaseZoom;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JButton increaseZoom;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea scale;
    // End of variables declaration//GEN-END:variables

    //Metodo para selecionar o arquivo SHAPE
    private File getFile(){
		JFileChooser fileChooser = new JFileChooser();
		fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
		fileChooser.addChoosableFileFilter(new ShapeFileFilter());
		int result = fileChooser.showOpenDialog(this);

		if (result == JFileChooser.CANCEL_OPTION)
		{
			return null;
		}

		File fileName = fileChooser.getSelectedFile();

		if ( (fileName == null) || (fileName.getName().equals("")))
		{
			JOptionPane.showMessageDialog(this, "Nome Invalido", "ERRO", 0);
		}

		return fileName;
	}
}



